---
image:
  tag: v${tag}

cloudProvider: aws
awsRegion: ${region}
autoDiscovery:
  clusterName: ${cluster_name}
  tags:
    - k8s.io/cluster-autoscaler/enabled
    - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}

extraArgs:
  balance-similar-node-groups: 'true'
  skip-nodes-with-system-pods: 'false'
  skip-nodes-with-local-storage: 'false'
  expander: 'least-waste'